development:
  host: 127.0.0.1
  adapter: postgresql
  encoding: unicode
  database: dom
  pool: 5
  username: app
  password: x3510

test:
  adapter: postgresql
  encoding: unicode
  database: myapp_test
  pool: 5
  username: myapp
  password: password1
